# Generated by Django 4.0.4 on 2022-06-01 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='detailed_description',
            new_name='detailedDescription',
        ),
        migrations.RenameField(
            model_name='skill',
            old_name='short_description',
            new_name='shortDescription',
        ),
    ]
