# Generated by Django 4.0.4 on 2022-06-03 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_detailed_description_skill_detaileddescription_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('detailedDescription', models.TextField()),
                ('shortDescription', models.CharField(max_length=300)),
            ],
        ),
    ]
